Added prompt for a branch description on feature start or hotfix start.

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -210,7 +210,12 @@ F,[no]fetch      Fetch from origin before performing local operation
 
 
 	# create branch
-	git_do checkout -b "$BRANCH" "$base" || die "Could not create feature branch '$BRANCH'."
+	if ! git_do checkout -b "$BRANCH" "$base"; then
+	  die "Could not create feature branch '$BRANCH'."
+	else
+	  git_do branch --edit-description
+	fi
+
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH" "$base"
 
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -211,7 +211,12 @@ F,[no]fetch       Fetch from origin before performing local operation
 	run_pre_hook "$VERSION_PREFIX$NAME" "$ORIGIN" "$BRANCH" "$base"
 
 	# Create branch
-	git_do checkout -b "$BRANCH" "$base"  || die "Could not create hotfix branch '$BRANCH'."
+	if ! git_do checkout -b "$BRANCH" "$base"; then
+	  die "Could not create hotfix branch '$BRANCH'."
+	else
+	  echo 'Enter the JIRA story id if you like (e.g., APP-1234):'
+	  git_do branch --edit-description
+	fi
 
 	run_post_hook "$VERSION_PREFIX$NAME" "$ORIGIN" "$BRANCH" "$base"
 
